---
title: "Xonotic: The Free and Fast Arena Shooter"
params:
  author:
    name: Xonotic Team
copyright: This website is licensed under the GNU Affero General Public License v3.0 except for components released under other licenses as noted in their respective sub-directories.
languageCode: en-us

rssLimit: 16
indexes:
  category: "categories"
  tag: "tags"

baseurl: "https://xonotic.org/"

markup:
  goldmark:
    renderer:
      # xonotic.org includes inline html which is disabled by default in goldmark
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3

imaging:
  quality: 100
  resampleFilter: Lanczos
---
